### ISSUE TITLE
Add a way to target all tasks matching a given pattern

### ISSUE THREAD

**Issue by k88hudson** [mysticatea/npm-run-all#1]
I was just thinking it would be nice to target all subtasks like `build:foo` `build:bar` and run them in parallel... is this something you've considered/a use case you're interested in?

**Comment by mysticatea** [comment]
I apologize for too late (I had missed the notification, and has found by #2's).
Thank you for the writing.

I agree, we want to specify tasks by pattern matching.
I will consider glob-like notations: `"build:*"`, `"build:**:*"`, ...
Maybe, the implementation becomes one such as that names are replaced `:` to `/` and are matched by [minimatch](https://www.npmjs.com/package/minimatch).

**Comment by mysticatea** [comment]
I implemented!

**Comment by k88hudson** [comment]
Thanks, I will try it out :+1:
