### ISSUE TITLE
[yarn] Doesn't seem to support this installation path

### ISSUE THREAD

**Issue by timwis** [mysticatea/npm-run-all#100]
Hey folks, I'm running a docker container using the [node-yarn-app](https://hub.docker.com/r/jsixc/node-yarn-app/~/dockerfile/) image, and my `start` script is set to `run-p start:*`. It's failing with the error:

```
Error: Cannot find module '/bin/yarn.js'
     ... (stack trace)
ERROR: "start:server" exited with 1.
```
When I set the `start` script to the value of `start:server` or the value of `start:client`, it runs fine. It's only when I introduce `npm-run-all` or `run-p` that I get this error. Per #68 I've tried setting `NPM_EXECPATH` to `/usr/local/bin/yarn` but that had no effect. My guess is that `npm-run-all` is looking in `/bin` instead of `/usr/local/bin`, though I'm not sure why.

Thanks for your help.

**Comment by mysticatea** [comment]
Thank you for this issue.

However, probably this is the problem of `yarn` of the docker container.
`npm-run-all` uses the program that `npm_execpath` specified, so if `npm_execpath` says a false location then `npm-run-all` cannot work properly. The `npm_execpath` is set by `yarn` itself in such `yarn run` command. In your case, `yarn` sets `/bin/yarn.js` to the `npm_execpath` but it does not exist.

An workaround, you can overwrite the location of `yarn`:

    $ npm-run-all -p start:* --npm-path /usr/local/bin/yarn

**Comment by timwis** [comment]
Thanks I'll give that a shot. For what it's with I tried setting the environment variable via the Docker compose file, and it reflected the result of `which yarn`.

**Comment by mysticatea** [comment]
Yeah, I guess `yarn run`/`yarn start` command will overwrite the environment variable.

**Comment by timwis** [comment]
Including `--npm-path /usr/local/bin/yarn` did the trick - thanks!

**Comment by timwis** [comment]
Although yarnpkg/yarn#2843 sounds like they'd patched this :/
