### ISSUE TITLE
Put name of script running before each line written to stdout?

### ISSUE THREAD

**Issue by mmkal** [mysticatea/npm-run-all#109]
I'm using this a lot to run scripts in parallel on travis-ci, and sometimes when they fail it'd be nice to see which script we're looking at. Is there anyway this library could fiddle with stdout and stderr so it'd print something like 

```
[[npm-run-all:lint]] line 23 is missing a semicolon
[[npm-run-all:test]] test foo failed
```

This would make it a lot easier to read through logs and understand what went wrong.

I guess there'd also need to be a way to configure it, which I haven't thought of yet. But what do you think of the idea?

**Comment by mysticatea** [comment]
Thank you for this issue.

Are you talking about `--print-label` option?

https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md

**Comment by misha-kaletsky-zocdoc** [comment]
Yes. Don't know how I missed that.

**Comment by mmkal** [comment]
Yes. Don't know how I missed that!
