### ISSUE TITLE
npm-run-all restart -> Matched tasks not found

### ISSUE THREAD

**Issue by leftiness** [mysticatea/npm-run-all#11]
Like it says on the tin. `npm-run-all restart` throws an error if you haven't explicitly defined a restart task. There's a [built-in npm task](https://docs.npmjs.com/cli/restart) for restart. I can just add a task that does the same thing, but maybe npm-run-all should recognize the built-in task.

**Comment by mysticatea** [comment]
Thank you for reporting!

I had not noticed built-in tasks.
Are there other built-in tasks?

**Comment by mysticatea** [comment]
`restart` and `env` seem to be built-in.
I supported those in `v1.2.12`, please try!

**Comment by leftiness** [comment]
I can confirm that `npm-run-all restart` works now. In the end, I decided to use my own start:dev, stop:dev, and restart:dev tasks separately from start, stop, and restart because the *:dev tasks also include things like watchify, but your quick response to this opened issue was admirable. Good work! :)
