### ISSUE TITLE
Process never finish with --aggregated-output 

### ISSUE THREAD

**Issue by jlopezxs** [mysticatea/npm-run-all#111]
### Details
When I execute many tests in jest with the `--coverage` flag and `--aggregated-output` the process stays in waiting and doesn't launch the exit code.

### Expected Behavior
Execute all the command properly.

### Actual Behavior
The process never ends.

### Possible Fix
Doing some test if I change the package `memory-streams` for `memorystream` everything works well.

```
//const writer = new streams.WritableStream()
const writer = new MemoryStream();
```
https://github.com/JSBizon/node-memorystream

### Your Environment
Node: v8.1.4
SO: Mac OS

**Comment by mysticatea** [comment]
Thank you for this issue.

`--aggregated-output` depends on a number of outputs and the memory of your machine since it accumulates all outputs then prints those after all tasks have done.
If the `memory-streams` package is using superfluous memory, I should check it and replace it.
