### ISSUE TITLE
Failure to find ../common/bootstrap when running on Linux

### ISSUE THREAD

**Issue by amclin** [mysticatea/npm-run-all#118]
I keep getting this error when trying to use npm-run-all on a Linux machine, but do not see it on OSX. Same version of npm (5.5.1) on both, same version of Node.JS (8.9.3) on both:

`

08-Dec-2017 17:15:30 | > npm-run-all lint:*
-- | --
08-Dec-2017 17:15:30 |  
08-Dec-2017 17:15:30 | module.js:538
08-Dec-2017 17:15:30 | throw err;
08-Dec-2017 17:15:30 | ^
08-Dec-2017 17:15:30 |  
08-Dec-2017 17:15:30 | Error: Cannot find module '../common/bootstrap'
08-Dec-2017 17:15:30 | at Function.Module._resolveFilename (module.js:536:15)
08-Dec-2017 17:15:30 | at Function.Module._load (module.js:466:25)
08-Dec-2017 17:15:30 | at Module.require (module.js:579:17)
08-Dec-2017 17:15:30 | at require (internal/module.js:11:18)
08-Dec-2017 17:15:30 | at Object.<anonymous> (/root/bamboo-agent-home/xml-data/build-dir/ATP-UV2741-JUT/node_modules/.bin/npm-run-all:13:1)
08-Dec-2017 17:15:30 | at Module._compile (module.js:635:30)
08-Dec-2017 17:15:30 | at Object.Module._extensions..js (module.js:646:10)
08-Dec-2017 17:15:30 | at Module.load (module.js:554:32)
08-Dec-2017 17:15:30 | at tryModuleLoad (module.js:497:12)
08-Dec-2017 17:15:30 | at Function.Module._load (module.js:489:3)
08-Dec-2017 17:15:30 | npm ERR! code ELIFECYCLE
08-Dec-2017 17:15:30 | npm ERR! errno 1
08-Dec-2017 17:15:30 | npm ERR! vfdp-html@4.25.0 lint: `npm-run-all lint:*`
08-Dec-2017 17:15:30 | npm ERR! Exit status 1
08-Dec-2017 17:15:30 | npm ERR!
08-Dec-2017 17:15:30 | npm ERR! Failed at the vfdp-html@4.25.0 lint script.
08-Dec-2017 17:15:30 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
08-Dec-2017 17:15:30 |  
08-Dec-2017 17:15:30 | npm ERR! A complete log of this run can be found in:
08-Dec-2017 17:15:30 | npm ERR!     /root/.npm/_logs/2017-12-08T23_15_30_404Z-debug.log
08-Dec-2017 17:15:30 | npm ERR! code ELIFECYCLE
08-Dec-2017 17:15:30 | npm ERR! errno 1
08-Dec-2017 17:15:30 | npm ERR! vfdp-html@4.25.0 pretest: `npm run lint`
08-Dec-2017 17:15:30 | npm ERR! Exit status 1
08-Dec-2017 17:15:30 | npm ERR!
08-Dec-2017 17:15:30 | npm ERR! Failed at the vfdp-html@4.25.0 pretest script.
08-Dec-2017 17:15:30 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

The file node_modules/npm-run-all/bin/common/bootstrap.js does exist, but the error above seems to indicate that npm-run-all gets run from node_modules/.bin, not node_modules/npm-run-all/bin.... so as a result, the file common/bootstrap.js doesn't exist

**Comment by amclin** [comment]
I should clarify that this is locally installed to the project (not global install) and is being triggered from an npm command defined in package.json thusly:
`"lint": "npm-run-all lint:*"`

**Comment by amclin** [comment]
To help with troubleshooting, there are lots of other modules in .bin that use the **require("../** pattern. But npm-run-all, run-p, and run-s are the only ones using the pattern **require("../relative/file")("module")** 

https://github.com/mysticatea/npm-run-all/blob/02e97675e3852aefd758d40fef366dc3be5b7aad/bin/npm-run-all/index.js#L13

**Comment by mysticatea** [comment]
Thank you for this issue.

You seemed to fail to install. Please try to:

- Re-install npm-run-all.
- If it's still failing, remove npm's cache and re-install npm-run-all.
- If you are using a folder which is synchronized to cloud storage (e.g. Dropbox), disable the sync and re-install npm-run-all. As far as I know, Dropbox sync breaks node_modules folder.

**Comment by mysticatea** [comment]
Anyway, this looks a problem in npm.
If you could not solve the problem, I recommend opening an issue on https://github.com/npm/npm.

Thank you.

**Comment by amclin** [comment]
@mysticatea thank you for the quick response

But I don't think this is an NPM problem. It only happens with this module (I pointed out how your module differs from every other one I've seen). It happens on multiple versions of Node/NPM (replicated with older versions as far back as Node 2.X) and I've seen it happening on multiple machines (the commonality is Linux instead of OSX). Reinstalling NPM, flushing caches, and reinstalling npm-run-all does not solve the issue.

Dropbox (or similar) filesync is not being used. Every machine is running a typical `npm install` to download and locally install the modules into the project workspace.

I think you are depending on a module or pattern that does not consistently behave the way you think it does across all filesystems. Not all filesystem behaviors can be abstracted by Node/NPM.

**Comment by amclin** [comment]
Here are the warnings from NPM install (notice warnings only, no errors) - the only one I can discern that might be related are those for fsevents

`

08-Dec-2017 18:46:13 | npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
-- | --
08-Dec-2017 18:46:13 | npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
08-Dec-2017 18:46:14 | npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
08-Dec-2017 18:46:15 | npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
08-Dec-2017 18:46:15 | npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
08-Dec-2017 18:46:15 | npm WARN deprecated coffee-script@1.8.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
08-Dec-2017 18:46:16 | npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)


08-Dec-2017 18:46:32 | npm notice created a lockfile as package-lock.json. You should commit this file.
-- | --
08-Dec-2017 18:46:32 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
08-Dec-2017 18:46:32 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


`

**Comment by mysticatea** [comment]
I disagree. 

- I'm using this package on Linux while a long time.
- Your suggestion is not related to path resolving. `require(...)()` is just a function call of the imported function. It's the same as `var f = require(...); f();`.

**Comment by amclin** [comment]
@mysticatea I have totally stripped this down to remove all dependencies. The only module include is npm-run-all, which I am forcibly installing via URL to guarantee it's not coming from npm cache. No errors or warnings on npm install. There are no other modules beyond what npm-run-all includes, yet it still presents the error:
https://gist.github.com/amclin/c0438a43682d3afbcb9e91e49101fa0b

**Comment by mysticatea** [comment]
Could you try `node node_modules/npm-run-all/bin/npm-run-all lint:*`? If it works, this is a problem of npm because to create `.bin/npm-run-all` correctly is the responsibility of npm. If it does not work, I guess some files are lacking for some reason. It also is an installation problem.

**Comment by amclin** [comment]
Thanks for staying with this @mysticatea . When I run the command like that, it fails with the same error. I've been doing more digging now that I have the sysadmin for the server online and helping me. It does appear to be a disconnect where the npm install was run on one sever/location, and then the npm scripts run after that workspace was copied to a different server/location. We had initially ruled out stuff being moved around because the install and run steps were happening on the same box, but it appears we were wrong.

Thanks again for your support, I do appreciate it.

**Comment by Enalmada** [comment]
I just tried this on beanstalk and failed.  "concurrently" also fails with a different error.  Has anyone figured out something that works?

**Comment by mrozekma** [comment]
Don't think it applies to anyone who's commented so far, but note that this can happen if you've copied `node_modules` without preserving symlinks, so your `.bin` is full of scripts instead of links to scripts; then the relative path to `../common/bootstrap.js` doesn't work anymore

**Comment by kublaios** [comment]
> Don't think it applies to anyone who's commented so far, but note that this can happen if you've copied `node_modules` without preserving symlinks, so your `.bin` is full of scripts instead of links to scripts; then the relative path to `../common/bootstrap.js` doesn't work anymore

+1, this actually happened to me after I moved the project to another folder.

**Comment by doughorne** [comment]
> Don't think it applies to anyone who's commented so far, but note that this can happen if you've copied `node_modules` without preserving symlinks, so your `.bin` is full of scripts instead of links to scripts; then the relative path to `../common/bootstrap.js` doesn't work anymore

+1, I just deleted the node_modules folder and did a npm install. Back up and running now.

**Comment by wzr1337** [comment]
> Don't think it applies to anyone who's commented so far, but note that this can happen if you've copied `node_modules` without preserving symlinks, so your `.bin` is full of scripts instead of links to scripts; then the relative path to `../common/bootstrap.js` doesn't work anymore

You made my day!!!

**Comment by ArianHojatAES** [comment]
Where is common/boostrap.js suppose to exist? I am deploying my code via a CodePipeline (setup initially via Terraform) into AWS. I am not copying node_modules/ so i dont think i have the issue mentioned above with symlinks not being preserved.

looking at my node_modules/.bin/npm-run-all, I only see this:
```
#!/usr/bin/env node
"use strict"
require("../common/bootstrap")("npm-run-all")

```
Above implies there should be a common/ dir inside of node_modules/ but i don't see it.

Here is the error i see in my AWS EC2 server's logs:
```
Oct 13 23:00:04 ip-192-170-2-87 web: > npm-run-all build server
Oct 13 23:00:04 ip-192-170-2-87 web: node:internal/modules/cjs/loader:959
Oct 13 23:00:04 ip-192-170-2-87 web: throw err;
Oct 13 23:00:04 ip-192-170-2-87 web: ^
Oct 13 23:00:04 ip-192-170-2-87 web: **Error: Cannot find module '../common/bootstrap'**
Oct 13 23:00:04 ip-192-170-2-87 web: Require stack:
Oct 13 23:00:04 ip-192-170-2-87 web: - /var/app/current/node_modules/.bin/npm-run-all
Oct 13 23:00:04 ip-192-170-2-87 web: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
Oct 13 23:00:04 ip-192-170-2-87 web: at Function.Module._load (node:internal/modules/cjs/loader:804:27)
Oct 13 23:00:04 ip-192-170-2-87 web: at Module.require (node:internal/modules/cjs/loader:1028:19)
Oct 13 23:00:04 ip-192-170-2-87 web: at require (node:internal/modules/cjs/helpers:102:18)
Oct 13 23:00:04 ip-192-170-2-87 web: at Object.<anonymous> (/var/app/current/node_modules/.bin/npm-run-all:13:1)
Oct 13 23:00:04 ip-192-170-2-87 web: at Module._compile (node:internal/modules/cjs/loader:1126:14)
Oct 13 23:00:04 ip-192-170-2-87 web: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
Oct 13 23:00:04 ip-192-170-2-87 web: at Module.load (node:internal/modules/cjs/loader:1004:32)
Oct 13 23:00:04 ip-192-170-2-87 web: at Function.Module._load (node:internal/modules/cjs/loader:839:12)
Oct 13 23:00:04 ip-192-170-2-87 web: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
Oct 13 23:00:04 ip-192-170-2-87 web: code: 'MODULE_NOT_FOUND',
Oct 13 23:00:04 ip-192-170-2-87 web: requireStack: [ '/var/app/current/node_modules/.bin/npm-run-all' ]
```

EDIT:
The common/bootstrap file is in this directory (not in .bin though)... Should a copy of it been copied to node_modules/.bin too?:
```
sh-4.2$ ls -al node_modules/npm-run-all/bin/common/
total 16
drwxr-xr-x 2 webapp webapp   69 Oct 13 22:59 .
drwxr-xr-x 6 webapp webapp   65 Oct 13 22:59 ..
-rw-r--r-- 1 webapp webapp 1482 Oct 13 22:59 bootstrap.js
-rw-r--r-- 1 webapp webapp 7280 Oct 13 22:59 parse-cli-args.js
-rw-r--r-- 1 webapp webapp  684 Oct 13 22:59 version.js
```
