### ISSUE TITLE
Fails when combined with a script that uses ECHO on linux

### ISSUE THREAD

**Issue by IAMtheIAM** [mysticatea/npm-run-all#119]
On linux  Alpine, if I have a script like this;:

```
    "install-msg:globals": "echo \n\n==============================================\n\n Installing Global NPM packages... \n\n==============================================\n\n",

```
then I do `run-s install-msg:globals install:packages`

It errors out with

```
> echo

==============================================

Installing Global NPM packages...

==============================================



sh: ==============================================: not found
sh: Installing : not found
sh: ==============================================: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

It works fine on windows though. What is the workaround for using ECHO statements in a series of `run-s` commands?

**Comment by mysticatea** [comment]
I guess your intention is:

- enclose the text by double quotes:

        "install-msg:globals": "echo \"\n\n==============================================\n\n Installing Global NPM packages... \n\n==============================================\n\n\"",

- Or use multiple echo commands

        "install-msg:globals": "echo \necho \necho ==============================================\necho \necho  Installing Global NPM packages... \necho \necho ==============================================\necho \n",

Npm scripts are executed with `sh`, so line breaks mean the end of command.

**Comment by mysticatea** [comment]
Hmm. `echo` command doesn't seem cross-platform safe.

I guess you can use `"node -e \"console.log('hello')\""` instead if you want to use the script on cross-platform.

**Comment by IAMtheIAM** [comment]
Hey, thanks a lot!! it worked!

```
  "install-msg:globals": "echo \"\n\n==============================================\n\n Installing Global NPM packages... \n\n==============================================\n\n\"",
```

allowed the echo to output and not break bash.

**Comment by IAMtheIAM** [comment]
Also, do you think this package makes it safer to use echo?
[echo-cli](https://www.npmjs.com/package/echo-cli)

**Comment by mysticatea** [comment]
> But node -e console.log('\n\n==============================================\n\n Installing Local NPM packages... \n\n==============================================\n\n') failed with

It's like break problem as well :)
You should use `\\n` to give `\n` to Node.js.

> Also, do you think this package makes it safer to use echo?
> echo-cli

This package does not touch how to run the script. This just calls `npm run foo`. So if you want to improve npm-scripts, please open issues on npm/npm repository.

**Comment by IAMtheIAM** [comment]
Thanks for all the help. Its working as I need now ;-)
