### ISSUE TITLE
Same tasks are skipped

### ISSUE THREAD

**Issue by halt-hammerzeit** [mysticatea/npm-run-all#12]
My script is
```
npm-run-all delay delay delay development-web-server
```

```
"delay": "node ./code/delay 3000"
```

But it only delays for 3 seconds and then runs `development-web-server`.

```
> webapp@1.0.0 development-web-server-delayed G:\work\webapp
> npm-run-all delay delay delay development-web-server


> webapp@1.0.0 delay G:\work\webapp
> node ./code/delay 3000


> webapp@1.0.0 development-web-server G:\work\webapp
> nodemon ./code/web-server/entry.js
```

**Comment by halt-hammerzeit** [comment]
My workaround for those who google - duplicating tasks
https://github.com/remy/nodemon/issues/709#issuecomment-153893668

**Comment by mysticatea** [comment]
Thank you for reporting.

`npm-run-all` is removing duplication for when glob-like patterns are overlapped.
But I think it should not remove duplication of non glob-like patterns.
I will fix it.

By the way, `npm-run-all` can use arguments, so that can be written:

```json
{
    "development-web-server-delayed": "npm-run-all 'delay 9000' development-web-server",
    "delay": "node ./code/delay"
}
```

**Comment by halt-hammerzeit** [comment]
@mysticatea oh, the arguments feature is good, i'll use it in my code instead, thanks

**Comment by halt-hammerzeit** [comment]
@mysticatea thx for the fix. It works now with duplicates.

The initial suggestion didn't work
```
{
    "development-web-server-delayed": "npm-run-all 'delay 9000' development-web-server",
    "delay": "node ./code/delay"
}
```

(the delay script didn't even run)
but it doesn't matter since duplicates are working now
