### ISSUE TITLE
Run script contents directly instead of through `npm run`

### ISSUE THREAD

**Issue by Siilwyn** [mysticatea/npm-run-all#122]
Just came across this tool [redrun](https://github.com/coderaiser/redrun), found the benchmarks very interesting. Would it be an idea to speed up `npm-run-all` by running the contents of each script directly in a similar fashion?

**Comment by mysticatea** [comment]
Thank you for this issue.

I know that `npm-run-all` is slow. However, I'm not active to clone the `npm run-scripts` behavior because it's pretty complex -- pre/post scripts, some embedded scripts (`env`/`restart`,...), ton of environment variables that `npm` set, and multi-platform.

**Comment by Siilwyn** [comment]
🤔 understandable, looking at redrun's code it doesn't seem that complex... but it probably doesn't fully emulate the `npm run` behavior.

Btw. it's more like `npm run` is slow rather than `npm-run-all`.
