### ISSUE TITLE
Does not accept --args when using Argument placeholders

### ISSUE THREAD

**Issue by CxRes** [mysticatea/npm-run-all#128]
I am trying to run:
```
"build:a": "node ./scripts/a",
"build": "npm-run-all \"build:a -- {@}\" --"
```
and I `console.log(process.argv.slice(2))` in `build:a` script.

With input:
```
npm run build -- --foo bar
```
my output is:
```
[bar]
```

I am not sure if it is a bug or intended behaviour, but it would be nice to get the entire argument chain without asking user to wrap args in quotes.

**Comment by mysticatea** [comment]
Thank you for this issue.

However, I could not reproduce it.

```
~\dev\sandbox> npm run build -- --foo bar

> sandbox@1.0.0 build C:\Users\t-nagashima.MSS\dev\sandbox
> npm-run-all "build:a -- {@}" -- "--foo" "bar"


> sandbox@1.0.0 build:a C:\Users\t-nagashima.MSS\dev\sandbox
> node index.js "--foo" "bar"

[ '--foo', 'bar' ]
```

Would you provide your environment and the actual output of npm?

**Comment by CxRes** [comment]
@mysticatea I am sorry, but I seem to have made a mistake. I looked back into my shell history in the morning and found that the example I have been using was more similar to this:
```
npm run build --foo bar -- baz --cuux
```

and my output is:
```
> node ./scripts/a "bar" "baz" "--cuux"

[ 'bar',  'baz',  '--cuux' ]
```

As you had seen I had missed the `--` and that was what had confused me. However, I also think why that might have left me confused. `npm run` seems to pass the undashed `bar` argument before the double dash. I wounder if this is the way shells work or if this a bug in `npm run`. I say this because `npm run` doc categorically states that it passes arguments only after the `--` argument. What do you think?

As for env:
I am on node 8.9.4(LTS), npm 5.6.0, Windows 10 Pro x64

**Comment by mysticatea** [comment]
I agree that it's confusing behavior of `npm run-script`. But I guess it may be for backward compatibility.

**Comment by CxRes** [comment]
Filed a bug with npm: npm/npm/issues/19898
