### ISSUE TITLE
Question: How to trigger something sequential after watch

### ISSUE THREAD

**Issue by yogeshgadge** [mysticatea/npm-run-all#132]
How to accomplish the following

```
"npm-run-all  clean  build:watch serve"
```

In this case the build:watch keeps watching and sere will never execute.

Using parallel has a different problem:

```
"npm-run-all  clean  -p build:watch serve"
```

server occurs too soon before build:watch has produced the distribution.

In the next approach using build and build:watch triggers the build twice and now I am having to adjust buid:watch to not trigger until the run:

```
"npm-run-all  clean  build -p build:watch serve"
```

So what is the elegant solution here ?

**Comment by pushred** [comment]
I had a similar issue where I needed a build file to be generated before a server started and the recommendation in #123 to use [wait-on](https://www.npmjs.com/package/wait-on) solved this perfectly👌

**Comment by yogeshgadge** [comment]
Will use wait-on
