### ISSUE TITLE
ERROR: build:before: None-Zero Exit(7);

### ISSUE THREAD

**Issue by e-jigsaw** [mysticatea/npm-run-all#14]
Hi,

My project's `package.json` is

```
  "config": {
    "DEST": "build",
    "PORT": "3000"
  },
  "scripts": {
    ...
    "build:before": "mkdir -p $npm_package_config_DEST",
    ...
  }
```

`build:before` task is just making directory.

```
$ npm run build:before
...
$ echo $?
0
$ npm-run-all build:before
...
ERROR: build:before: None-Zero Exit(7);
...
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
```

v1.2.13 works fine but v1.3.0 has been broken :(

Any suggestions?

Thanks

**Comment by misteroneill** [comment]
Confirming that I'm seeing this on any script that uses `npm-run-all`, but running the scripts individually has no issues.

**Comment by alicoding** [comment]
I'm seeing the same problem here. It looks like this happened after the code refractor patch...

**Comment by mysticatea** [comment]
Oh my God, I apologize for it.
For a first aid, I reverted to `v1.2.13` and published as `v1.3.1`.

My bad, I had not been having tests for stdin/stdout, so these were not tested in Travis CI.

**Comment by mysticatea** [comment]
@janl Thank you for investigating.

Hmm, I seem to need changing my strategy that I use process group id to kill child processes.

**Comment by mysticatea** [comment]
Hmm, I'm trying to add tests for this bug, but it works in Travis CI...
This might be related with nodejs/node#3596

**Comment by e-jigsaw** [comment]
@mysticatea Thanks for great support!

**Comment by misteroneill** [comment]
:+1:

**Comment by janl** [comment]
nice! <3
