### ISSUE TITLE
Output when using API

### ISSUE THREAD

**Issue by jefe-spain** [mysticatea/npm-run-all#140]
Within a script; I'm not really sure but how It's possible to show the output of the script called using the Node API. It's perfoming the task but I don't see any progress at all.

**Comment by raDiesle** [comment]
So I figured out this is some standard setup how you usually want to handle the output, in my case of plugin:

`
const commandForFormat = isCi ? 'verifyFormat' : 'format';
runAll([commandForFormat], {
  parallel: false,
  printLabel: true,
  stdout: process.stdout,
  stdin: process.stdin,
  stderr: process.stderr,
})
  .then(() => {
    console.info(`"${commandForFormat}" of code was successful.`);
  })
  .catch((err) => {
    process.exit(0);
  });`
