### ISSUE TITLE
npm install npm-run-all --save-dev Corrupted issue

### ISSUE THREAD

**Issue by ayami123** [mysticatea/npm-run-all#141]
![image](https://user-images.githubusercontent.com/17733287/44769287-b8487300-ab96-11e8-805c-56769fd0e47c.png)

 
Is this from me, Or is this in all npm install issue ?

**Comment by mysticatea** [comment]
Looks like a npm's problem.
`npm-run-all` doesn't depend on `hoek` both directly and indirectly, but the error message is about `hoek` package.
