### ISSUE TITLE
non-zero exit codes

### ISSUE THREAD

**Issue by ronkorving** [mysticatea/npm-run-all#15]
From the code, I believe to understand that non-zero exit codes abort a sequential series of tasks. If true (or if different), it would be nice if that were documented.

**Comment by mysticatea** [comment]
Yes, you are right.
Document is lacking now.

**Comment by ronkorving** [comment]
Thanks from Tokyo, Chuo-ku ;)

**Comment by mysticatea** [comment]
Wow, it's near! (I'm in Shizuoka)

Thank you very much!

**Comment by ronkorving** [comment]
Cool! :)

**Comment by ronkorving** [comment]
Thanks for fixing the docs
