### ISSUE TITLE
Vulnerability in event-stream dependency

### ISSUE THREAD

**Issue by ChrisBAshton** [mysticatea/npm-run-all#150]
There's a serious vulnerability in [event-stream](https://github.com/dominictarr/event-stream/issues/116), which is used by npm-run-all.

Please consider locking into v3.3.4 or lower, which appears to be before the vulnerability was introduced.

EDIT: the vulnerable package is pulled in via your dependency `ps-tree`, which has an issue open to fix it: https://github.com/indexzero/ps-tree/issues/33

**Comment by mysticatea** [comment]
Thank you for the report.
But I have already published [v4.1.5](https://github.com/mysticatea/npm-run-all/releases/tag/v4.1.5) to address it.

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read the thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34

**Comment by code-for-coffee** [comment]
@mysticatea thank you so much for being on top of this issue.
