### ISSUE TITLE
Malicious dependency?

### ISSUE THREAD

**Issue by jeremyrajan** [mysticatea/npm-run-all#153]
Hi @mysticatea ,

Thanks a lot for the lib :). I was reading through the latest vulnerability that was reported here:
1. https://www.theregister.co.uk/2018/11/26/npm_repo_bitcoin_stealer/
2. https://github.com/dominictarr/event-stream/issues/116

(2) explains more in detail regarding the dependency. I ran the checks, and seems one of the versions has that...
![image](https://user-images.githubusercontent.com/2890683/49072912-469ec480-f26c-11e8-8605-2b078f58995d.png)

Should this be dealt with? Or is it already patched :).

Thank you!

**Comment by deniaz** [comment]
We're now even seeing errors in our CI pipeline since `flatmap-stream` was removed from the registry:

```
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.1
```

**Comment by isnifer** [comment]
@jeremyrajan just upgrade to 4.1.5

**Comment by jeremyrajan** [comment]
yup that works @isnifer! thank you 👍
