### ISSUE TITLE
Issue with dependency on flatmap-stream via ps-tree

### ISSUE THREAD

**Issue by darklingChaz** [mysticatea/npm-run-all#155]
npm-run-all is trying to pull down flatmap-stream as a dependency of ps-tree@1.1.0. 

flatmap-stream has been removed from npm. See https://github.com/remy/nodemon/issues/1468.

Newest version ps-tree@1.1.2 is fixed.

- sorry, don't have time to fork and request  :(

**Comment by TehShrike** [comment]
Duplicate of #149, #150, #152, #153, #154

This was fixed in v4.1.5

**Comment by darklingChaz** [comment]
Cheers!
