### ISSUE TITLE
`--silent` flag isn't working properly

### ISSUE THREAD

**Issue by ivancuric** [mysticatea/npm-run-all#162]
I'm running typescript in `noEmit` mode to do a typecheck.

```
"typecheck": "tsc -p .",
"ts:silent": "run-s --silent typecheck",
```

While `npm run -s typecheck` works, both `npm run typecheck` and `npm run ts:silent` produce an error output:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@0.0.0 ts:silent: `run-s --silent typecheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myproject@0.0.0 ts:silent script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ivan/.npm/_logs/2019-02-11T15_06_16_069Z-debug.log
```

Using the `|| true` hack isn't an option due to development being done in Windows, and neither is setting up a `.npmrc` with `loglevel=silent`

**Comment by mysticatea** [comment]
Thank you for this issue.

However, this is working correctly. The log you saw is the log of `npm run ts:silent` rather than `npm run typecheck` which is silent.

**Comment by ivancuric** [comment]
Is there any way `npm-run-all` can help with avoiding the log? Eg, replacing the `|| hack`?

**Comment by mysticatea** [comment]
No. It cannot affect how the parent process works.
