### ISSUE TITLE
Broken on node 0.10.x (@v1.3.3)

### ISSUE THREAD

**Issue by moqada** [mysticatea/npm-run-all#17]
`babel-polyfill` exists package.json as dependencies.
But, it is never imported from production code.

I think that it can solve by adding `require('babel-polyfill')` to `src/bin/npm-run-all.js` and `index.js`.
What do you think?

Refs:

- [Job #119.1 - moqada/aws-sdk-config-loader - Travis CI](https://travis-ci.org/moqada/aws-sdk-config-loader/jobs/94564456)
- [Polyfill · Babel](https://babeljs.io/docs/usage/polyfill/)

**Comment by mysticatea** [comment]
Oh, thank you for the issue.
I'm wondering why my Travis CI is green.
I will fix this.

**Comment by mysticatea** [comment]
Hmm, I'd like to use `babel-runtime` and `babel-plugin-transform-runtime` because I want to keep clean global scope, but I'm encountering with https://phabricator.babeljs.io/T6644

**Comment by mysticatea** [comment]
For now, I add `import "babel-polyfill";` to `bin/npm-run-all.js`, and I confirm it works on Node.js v0.10.41.
I published it as v1.3.4.
Please try it.

**Comment by moqada** [comment]
As you said, it looks more better if it can use `babel-runtime`...

But, v1.3.4 works fine!
Thanks!!

Refs:

- [Job #126.1 - moqada/aws-sdk-config-loader - Travis CI](https://travis-ci.org/moqada/aws-sdk-config-loader/jobs/95151065)
