### ISSUE TITLE
Feature request: Finally script

### ISSUE THREAD

**Issue by stsvilik** [mysticatea/npm-run-all#173]
Would be good to have an option to specify a task that would run regardless of the success/failure of other tasks. Think of a clean-up task that would shutdown service or docker at the end of the task.

Ex: `run-s -f stop:service start:service run:tests` - starts service > runs tests > stops service

**Comment by TehShrike** [comment]
Doesn't the semicolon work for this on every OS?

```
run-s start:service run:tests; npm run stop:service
```

**Comment by stsvilik** [comment]
@TehShrike huh, didn't check - should it :)?

**Comment by stsvilik** [comment]
@TehShrike that worked 👍

**Comment by Shingaz** [comment]
> Doesn't the semicolon work for this on every OS?
> 
> ```
> run-s start:service run:tests; npm run stop:service
> ```

This command returns the exit code from `npm run stop:service`. If you think `try...finally` you would expect the whole npm script to return the exit code from `run-s start:service run:tests`
