### ISSUE TITLE
Add support for `--silent`

### ISSUE THREAD

**Issue by micky2be** [mysticatea/npm-run-all#18]
npm command has this `--silent` option to avoid `npm test` to spit out npm errors when running npm command as a script. I found that really nice.
Would be nice for npm-run-all to have this options too.

**Comment by mysticatea** [comment]
Thank you for this issue.

I confirmed `npm run --silent foo` hides lines which start with `npm ERR!`.
It's really nice!

I will add the option to `npm-run-all`.

**Comment by mysticatea** [comment]
I added it!

https://github.com/mysticatea/npm-run-all/releases/tag/v1.5.0

**Comment by micky2be** [comment]
Great. Thank you
