### ISSUE TITLE
-s shorthand for --silent is missing on the parent npm-run-all binary

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mysticatea/npm-run-all#185]
At the moment, `run-p` et al have a `-s` form of the `--silent` flag, which is very helpful for (already-long) npm scripts.

Unfortunately, the parent `npm-run-all` binary only provides `--silent`, and doesn't recognize `-s`.

**Comment by gabrieldrs** [comment]
That's probably because `npm-run-all -s` is a shorthand for `npm-run-all --sequential <tasks>` [REF](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md)

**Comment by ELLIOTTCABLE** [comment]
Oh, ~Yikes~. Well, that's good to know, then! (Maybe `-S`, capitalized, would make a good shorthand for `--silent`, then? :x)
