### ISSUE TITLE
`--aggregate-output` seems to drop CLI colors on Windows

### ISSUE THREAD

**Issue by XhmikosR** [mysticatea/npm-run-all#199]
Hey, @mysticatea!

I'm experimenting with `aggregate-output` on https://github.com/twbs/bootstrap/pull/32907.

It works good, but I notice that the CLI colors are then dropped on Windows native CMD.

Is there any workaround? Or could this be easily fixed?

Thanks in advance!

**Comment by marekdedic** [comment]
Hi,
I'm getting the same issue on linux as well...

**Comment by Snaptags** [comment]
Why has this been closed? Would love to have the colored output as well.

**Comment by norbertsongin** [comment]
Same thing happening on macOS
