### ISSUE TITLE
Support node 0.10.x

### ISSUE THREAD

**Issue by k88hudson** [mysticatea/npm-run-all#2]
How do you feel about testing against/supporting node 0.10.x @mysticatea?

**Comment by k88hudson** [comment]
I'm happy to submit a PR, just wanted to hear your thoughts about this first

**Comment by mysticatea** [comment]
I welcome your PR!
I will look to it that don't miss notifications...

**Comment by mysticatea** [comment]
I merged #3 

This was my first experience of the merge operation on GitHub.
Thank you very much!
