### ISSUE TITLE
Feature request: more granular control

### ISSUE THREAD

**Issue by corysimmons** [mysticatea/npm-run-all#20]
```json
{
"start": "chokidar ./lib -c 'npm run tasks:dev' --initial",
"tasks:all": "npm-run-all build:* dev:*",
"tasks:dev": "npm-run-all dev:*",
"build:lint:eslint": "eslint --parser babel-eslint ./lib",
"build:lint:standard": "standard --parser babel-eslint ./lib/**/*",
"dev:scripts:babel": "babel --presets es2015 ./lib -d ./"
}
```

It'd be neat if I could chain `:` together.

I could have `build:*` tasks, `dev:*` tasks, `dev:styles:*` tasks, etc.

**Comment by corysimmons** [comment]
Oh, nevermind, I can by using more asterisks.

`npm run dev:*:*` works.

Might still be neat to remove the need for the extra colon/asterisk, but it's no biggie.

**Comment by mysticatea** [comment]
Or you can use the glob star: `dev:**`

**Comment by corysimmons** [comment]
haha, yeah I just read that in docs and was coming to comment that I'm an idiot. Sorry. =)
