### ISSUE TITLE
Recommended watcher?

### ISSUE THREAD

**Issue by corysimmons** [mysticatea/npm-run-all#21]
Is there a particularly good watcher for npm-run-all?

Out of the ones I've tried (watch, nodemon, chokidar-cli) I think I like chokidar-cli the best.

It kind of stinks it has to re-run the processes from scratch though.

Ideally there would be a watcher that could watch files that don't come equipped with their own watcher and update them without having to completely re-run their npm task.

![image](https://cloud.githubusercontent.com/assets/224636/12806394/a81dafe6-cad3-11e5-8e6f-272df0105fc8.png)

See? I'm watching `./lib` for changes, and when there are changes, I do the compilation step on the npm run scripts I have. Unfortunately it doesn't just compile these lightning fast, but has to restart the process.

I don't know if there's some super clever/cool way to watch, or if this is just something each CLI has to build into their own product, but if there is some super cool way to watch, please let me know. :+1: 

Does any of this make any sense or am I just rambling?

**Comment by mysticatea** [comment]
I'd like to recommend a use of watcher in each tool.

e.g.

- `babel -w` option
- `mocha -w` option
- `watchify`
- `cpx -w` option

And `npm-run-all` can execute those in parallel.

**Comment by corysimmons** [comment]
Okay, I think that's the best solution.

FWIW if you ever run into a task that doesn't happen to have a watch, chokidar-cli is pretty good.
