### ISSUE TITLE
--labeled-output option

### ISSUE THREAD

**Issue by mysticatea** [mysticatea/npm-run-all#23]
When I run tasks in parallel, I will see a mix of stdout of those tasks.
So labels would be useful to indicate that each line has outputted from which tasks.

```
$ npm-run-all --labeled-output --parallel task1 task2

[task1] hello
[task1] world
[task2] hey
[task1] !!
[task2] everyone.
```

This feature should be an option since it modifies the outputs of tasks.

**Comment by clonq** [comment]
Could you also add an option for printing the task number? e.g. [1/3]

**Comment by mysticatea** [comment]
@clonq Oops, I'm sorry, I missed your comment.

Hm, I think people may be confused in the numbers since the numbers' candidate exists 3 kinds.

- the index in command line arguments?
- the index in matched tasks of command line arguments? (we can use pattern matching)
- the index in definition of package.json?
