### ISSUE TITLE
Cannot run multiple tasks that use npm-run-all

### ISSUE THREAD

**Issue by lostm1nd** [mysticatea/npm-run-all#24]
Hello,

I am trying to slim down my build script with npm-run-all. What I really want to use is the pattern matching for running tasks which saves a lot of repeating npm runs.

The thing I am having trouble with is the following scenario:
```javascript
"copy": "npm-run-all copy:*",
  "copy:images": "copyfiles -u 1 app/images/**/*.* build",
  "copy:fonts": "copyfiles -u 1 app/fonts/**/*.* build",
"lint": "eslint app/scripts/**/*.js",
"browserify": "browserify app/scripts/main.js -o build/scripts/bundle.js  -d -t [ babelify ] -p [minifyify ]",
"build": "npm-run-all copy build:*",
  "build:styles": "pleeease-compile",
  "build:scripts": "npm-run-all lint browserify"
```

When I run 'npm run copy' everything works okay but trying to run 'npm run build' and the execution hangs on the copy task.

**Comment by mysticatea** [comment]
Thank you for this issue.

Hmm, I have never seen problems on nested `npm-run-all` command.
Could you share a repo to reproduce it?
I'd like to investigate this.

**Comment by lostm1nd** [comment]
Thanks for the fast reply.

You can check out this issue in the following app - https://github.com/lostm1nd/WebDevolopment/tree/master/Pizzeria-ES2015

**Comment by mysticatea** [comment]
Thank you!

Hmm, but I cannot reproduce it on my PC.
Could you tell me your environment?

This is mine:

- Windows 7 64bit
- Node v4.3.0
- npm v3.7.5
- npm-run-all v1.5.1
- copyfiles v0.2.1

![test2](https://cloud.githubusercontent.com/assets/1937871/13493672/c68489d0-e182-11e5-99fa-b2f96395ea87.gif)

**Comment by lostm1nd** [comment]
Mine is:
- Windows 7 64bit
- Node v5.4.1
- NPM v3.8.0 (just upgraded from v3.3.12 and still the same issue)
- npm-run-all and copyfiles are the same as you listed

**Comment by mysticatea** [comment]
Okey, I can reproduce it on MINGW64!

**Comment by mysticatea** [comment]
Hmmm, it's very strange.

```js
// ...
console.log("main 1")
let stdin;
try { stdin = process.stdin; } finally { console.log("main 1.5") }
console.log("main 2")
// ...
```

`process.stdin` getter stops the program.
console wrote `"main 1"` then stops.
I never see `"main 1.5"` and `"main 2"`.

**Comment by mysticatea** [comment]
I typed Enter key once while the program is stopping, then it continues.... :confused:

**Comment by lostm1nd** [comment]
These three lines of code work for me as expected. It does not hang:
```javascript
node index.js
1
1.5
2  
```

**Comment by mysticatea** [comment]
Ah, sorry, I talked about [this line](https://github.com/mysticatea/npm-run-all/blob/87aedbf187f2e554e9d6654c9475f4c93cd0ba91/src/bin/main.js#L115).
When `npm-run-all` hangs, `process.stdin` seems to never return (then, it will return after I typed Enter key).
I'm still investigating...

**Comment by mysticatea** [comment]
This is a small repro code.

I executed the following command on Git Bash for Windows, then the program will stop at `process.stdin` of `"child"`.

```
$ cmd /C="node test.js"
```

**test.js**

```js
"use strict";

const name = process.argv[2] || "parent";

console.log("before stdin:", name);
process.stdin;
console.log("after stdin:", name);

if (process.argv[2] !== "child") {
    require("child_process").spawn(
        process.argv[0],
        [process.argv[1], "child"],
        {stdio: "inherit"}
    );
}
```

**Comment by mysticatea** [comment]
I reported an issue: https://github.com/nodejs/node/issues/5620

Also, I got the idea of a workaround.
I'm writing it....

**Comment by mysticatea** [comment]
Done.

@lostm1nd Thank you for your help!

**Comment by lostm1nd** [comment]
@mysticatea Thank you for the time invested in the issue!
