### ISSUE TITLE
Cannot run parallel nodemon tasks

### ISSUE THREAD

**Issue by lostm1nd** [mysticatea/npm-run-all#25]
Hello again,
What I currently have problem with is the following code:
```javascript
"watch": "npm-run-all --parallel watch:*",
      "watch:html": "nodemon -w src/ --ext html --exec npm run copy:html",
      "watch:styles": "nodemon -w src/styles/ --ext css --exec npm run copy:css",
      "watch:scripts": "nodemon -w src/scripts/ --ext js --exec npm run browserify"
```

Running 'npm run watch' executes the tasks but then when I change the files tasks are not re-run. So far I have done it with parallelshell but I suppose npm-run-all --parallel should do the same thing, right?

I have updated the test project to include this build step - https://github.com/lostm1nd/WebDevolopment/tree/master/Pizzeria-ES2015

**Comment by mysticatea** [comment]
Thank you for this issue, and I'm sorry for the inconvenience.

I have using some commands of watching (e.g. `watchify`, `mocha -w`, `cpx -w`, ...) and they are working fine.
I'll investigate this.

**Comment by mysticatea** [comment]
I confirmed this issue on only MINGW64.
Mmm...

**Comment by mysticatea** [comment]
OK, this issue caused by the same reason as #24.
`process.stdin` has never returned in tasks.
