### ISSUE TITLE
Improving windows support

### ISSUE THREAD

**Issue by BarryThePenguin** [mysticatea/npm-run-all#26]
While investigating kentcdodds/webpack-validator#7, I've been looking into this project and it's claim of supporting windows. 

I've cloned the project and run the tests and have noticed a few of things in relation to windows support.

- Using Appveyor builds. This is essential for supporting windows as it allows tests to be run in a windows environment.
- Code coverage. There is a high percentage of code coverage, but I noticed that `spawn-win32.js` isn't in the coverage report.

The actual issue I have discovered is that `which-npm.js` is returning a path like the following
 - `C:\Program Files\nodejs\npm.CMD`

In windows paths are typically normalized to
- `C:\\Program Files\\nodejs\\npm.CMD`

This results in npm complaining with

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

I thought this might be an issue in `which`, but it appears `npm` is using this package with no apparent issues...

I'm happy to create pull requests in an attempt to resolve any of these issues

**Comment by mysticatea** [comment]
Thank you for this issue!

Actually, I'm a Windows user and I'm testing `npm-run-all` on my PC for Windows.
But I have not installed Node.js to a path which includes a space, so I had not noticed this problem.

- Adding AppVeyor CI is nice to me.
- Is this issue meaning `child_process.spawn(command)` does not support a command which includes a space?

**Comment by BarryThePenguin** [comment]
Great! I've done some more investigation and I believe it's related to [Spawning .bat and .cmd files on Windows](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows), as well as the space in the path.

I'm working on that right now.

After that I can send through setup for Appeyor too
