### ISSUE TITLE
Any reason why `serial` is not as an option 

### ISSUE THREAD

**Issue by sarbbottam** [mysticatea/npm-run-all#30]
The moment I saw `parallel`, next option that came to my mind, was `serial`. On error, realized, that it should `sequential`.

It would be great to have `serial` as a synonymous option for `sequential` 

Happy to raise a PR, if you are convinced.

Thanks!!

**Comment by mysticatea** [comment]
Thank you for the proposal.
I appreciate the PR.

Since I'm not familiar with English, I hadn't noticed that word...
