### ISSUE TITLE
Parallel tasks can't be killed in Git Bash on Windows

### ISSUE THREAD

**Issue by coryhouse** [mysticatea/npm-run-all#32]
Hitting Ctrl+C in Windows produces the prompt for "Terminate batch job (Y/N)?", but answering "Y" doesn't actually get you back a usable command line. 

For an example of this behavior:

1. Clone [React Slingshot](https://github.com/coryhouse/react-slingshot)
2. `npm install`
3. Run `npm start` in Git Bash for WIndows
4. Note that hitting Ctrl+C fails to return a usable command line.

**Comment by mysticatea** [comment]
Thank you for this issue.

But I cannot reproduce this.
Could you share more info? (node version, npm version, git bash version, ...)

![issue32](https://cloud.githubusercontent.com/assets/1937871/14007156/69219bd0-f1b7-11e5-8716-20f19f70e2b6.gif)

**Comment by coryhouse** [comment]
Ah! The new version Git Bash fixes it. It's an issue in 1.9.2 (yes, I hadn't updated in awhile!), but works great in 2,7.4. Thanks so much for taking the time!
