### ISSUE TITLE
Feature request: Print running task name

### ISSUE THREAD

**Issue by trygveaa** [mysticatea/npm-run-all#35]
When a npm script exits with a non-zero exit code, npm prints a huge warning (https://github.com/npm/npm/issues/8821). And when using npm or npm-run-all in another npm script, the warning appears twice if the inner script fails, making it even worse. These warnings can be suppressed by using the `--silent` flag, so it was nice that you added this flag to npm-run-all as well.

However, this flag also suppresses npms output of which command it is running. When only running one npm script, that doesn't matter much. But with npm-run-all you run multiple scripts, so I'd like to see which script it runs, to know how far along it is.

So it would be nice with a new option that makes npm-run-all print the task it will run right before it runs it (either the npm script name, or the npm script name and the command it expands to).

**Comment by mysticatea** [comment]
Thank you for this request.

Sounds good to me.
I thought `--silent-except-task-name` similarly with `--silent` but this is so long. Do you have any idea?

**Comment by trygveaa** [comment]
I'm not sure. The only thing I could think of when creating this was `--verbose`, but then you would have to call `--silent --verbose` which would probably be confusing to users.

Also, I think it would be more logical to keep the option separate from the `--silent` option (even though it may not be that useful alone). Maybe you could call it `--print-name`, and also add a one letter shorthand for `--silent --print-name`, for example `-n`?

**Comment by mysticatea** [comment]
Hmm, OK.

I thought it's good to stick it to silent option since npm prints script names by default, but `--print-name` seems to be better.

I will make it within a few days.

**Comment by trygveaa** [comment]
I'm thinking that each option should only do one thing (except the ones that combine options), which is why I suggested a separate one. If you rather want one for both, you could call it `--silent-with-name` (a bit shorter than your suggestion at least), and still add a shorthand for that (`-n` or another character).
