### ISSUE TITLE
Aggregate logs?

### ISSUE THREAD

**Issue by track0x1** [mysticatea/npm-run-all#36]
If i'm running multiple scripts in parallel, is there a way to aggregate the logs so they don't blend into one incomprehensible mess?

**Comment by mysticatea** [comment]
Thank you for this issue.

`npm-run-all` executes npm-scripts as inheriting stdio. If not so, some libraries to color CLI and tools that are using it would stop coloring CLI (refs #8). So this tool does not touch the outputs of npm-scripts, then npm-scripts send outputs to the shell directly.

**Comment by jwbay** [comment]
I would gladly give up coloring via a command line argument in favor of cleaner logs for run-p. Since the streams are already wrapped to be able to prepend them with the label, maybe it's possible to hold back the output until a script is complete?

**Comment by mysticatea** [comment]
I'm sorry for late.

Now, `npm-run-all` has `print-label` option which edits the outputs of npm-scripts.
So I think we can add the option to aggregate the outputs of npm-scripts and print later.

**Comment by JuanCaicedo** [comment]
Very interested in this! The last approach sounds very good to me. What would it take to make this happen? Maybe I can help

**Comment by fatso83** [comment]
I think I'll need to look into this when I have time, because the output mangling is the number one issue. An option that enables batching/delaying the output from the parallel tasks would get us the speed advantage, while giving us the sequential output.

**Comment by fatso83** [comment]
@fearphage, now the issue of overlapping output in parallel tasks is resolved :-)
