### ISSUE TITLE
Exit code when sub tasks fails with -P

### ISSUE THREAD

**Issue by kentor** [mysticatea/npm-run-all#37]
What do you think about having an option that will exit with a non zero code when one of the subtasks exits with an error when running with `-P`?

One use case I'm thinking of is running tests of different sub-projects in parallel. e.g. `npm test` runs `npm-run-all -P test:project1 test:project2`

We want the entire process to exit > 0 if one of those fail, but we want each one to finish because each generates a report for CI.

Right now, without `-c` it would exit too early, but with `-c` the exit code of the entire thing is 0.

**Comment by rstacruz** [comment]
:+1: — i'd like to have 2 watchers running (eg, watchify + brunch watch), and have everything abort when one of them fails. otherwise, one will keep running and I'm left to wonder why the other one doesn't work.

**Comment by mysticatea** [comment]
@kentor I'm under consideration now. I'm afraid that there are too many options.

@rstacruz Maybe it's default behavior of `npm-run-all`. By default, `npm-run-all` abort all tasks when one of them exited with an error.

**Comment by anddoutoi** [comment]
It would also be nice if `runAll(['lint:something', 'lint:anotherthing'], {continueOnError: true, stdout: process.stdout});` could return a iterable promise like `Promise.all` do. One could then do something like:

```JavaScript
runAll(…).then(function (results) {
  var errorsDetected = results.some(function (result) {
    return result.code === 1;
  });

  if (errorsDetected) {
    process.exit(1);
  }
});
```

This would give task and tool writers a lot of freedom and would probably not impact the API that much. The only API that would change is the fulfilled value returned. Today it seems to the result of the last task that ran.

**Comment by mysticatea** [comment]
I have a plan to release v2.0.0 with some breaking changes in next week.

- I will make `--continue-on-error` option not ignoring errors. It just continues running, then `npm-run-all` itself exits with a non zero code.
- Some options (`--print-name`, `--print-label`, `--continue-on-error`) apply the effect to only the current group of tasks, currently. I will make those options applying the effect to all groups.

Also, @anddoutoi 's idea is nice.
I will do it.

**Comment by mysticatea** [comment]
I'm sorry for my late.
I released it.
