### ISSUE TITLE
--print-label swallows colors

### ISSUE THREAD

**Issue by rodneyrehm** [mysticatea/npm-run-all#38]
output without `--print-label`:
![without-labels](https://cloud.githubusercontent.com/assets/186837/14777869/18e13888-0ad0-11e6-8954-5c8f7e8e43a9.png)

output with `--print-label`:
![with-labels](https://cloud.githubusercontent.com/assets/186837/14777868/18e08f6e-0ad0-11e6-9b5a-e6539b993ccc.png)

**Comment by mysticatea** [comment]
Thank you for this issue.

Yeah, this is a known limitation.
[chalk] will stop coloring when `stdout` is not TTY. `npm-run-all` cannot keep `stdout` of child processes as TTY if it adds labels to each line (`stdout` of child processes will become `pipe`).

I will add this to documents.

You can give `--color` option to tools (e.g. eslint) which are using [chalk] to revive coloring.

[chalk]: https://www.npmjs.com/package/chalk

**Comment by mysticatea** [comment]
I added: https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#known-limitations
