### ISSUE TITLE
End run-p process from within process

### ISSUE THREAD

**Issue by reggi** [mysticatea/npm-run-all#42]
I'm writing a ci test that needs to run two commands in parallel, one is the server, the other is the test. 

Using `run-p start test` I can start the server and run the test. There's a notable issue with getting that working here.

https://stackoverflow.com/questions/37466757/how-do-i-run-postmans-newman-in-ci-environment

But after all is said and done, and the `test` process finishes I need to exit the entire `run-p` process. Is there away to end the process from within the process?

What I need is sort of like.

```
run-p start "test && kill {this}"
```

**Comment by mysticatea** [comment]
Thank you for this issue.

Interesting.
Maybe `--race` option solves this.
When one script finished, `npm-run-all`/`run-p` kills other scripts.

**Comment by reggi** [comment]
@mysticatea Is `--race` an option? I'm getting `ERROR: Invalid Option: --race`. Is it implemented yet?

```
  "scripts": {
    "echo-hi": "echo 'hi'",
    "sleep-15": "sleep 15",
    "sleep-10": "sleep 10",
    "sleep-100": "sleep 100",
    "sleep-1": "sleep 1",
    "start": "run-p sleep-1 sleep-100 --race"
  },
```

**Comment by mysticatea** [comment]
Yup, I will add the option if it solves your problem :)

**Comment by carlin-q-scott** [comment]
Is this released yet on npm? I am also getting the error saying the option doesn't exist.
