### ISSUE TITLE
Feature request: wait for message on stdout before continuing

### ISSUE THREAD

**Issue by poislagarde** [mysticatea/npm-run-all#43]
Hey! I'm setting up a node server with TypeScript, and I'd like to spawn `tsc -w` (compile + watch .ts files) in parallel with `nodemon` (watch compiled .js files + restart server).
The problem is that I need to delay the spawning of `nodemon` until `tsc` is done compiling.

I think it would be very useful if we could tell `npm-run-all` to wait for a message to appear on stdout before continuing to spawn tasks.

What do you think? If you guys think it's a good idea I can try to put together a PR. Of course I could use some pointers in that case.

**Comment by mysticatea** [comment]
Thank you for this issue.

Hmm, sorry, I don't want to add the feature to wait for specified message.
I think it's too complex for CLI option.

There are some workarounds.

1. Does the first build before watching.

  ```json
  {
      "build": "tsc ...",
      "watch": "npm-run-all build -p watch:*",
      "watch:tsc": "tsc -w ...",
      "watch:nodemon": "nodemon ..."
  }
  ```

2. Wait for built files in `nodemon` command.
  https://stackoverflow.com/questions/37466757/how-do-i-run-postmans-newman-in-ci-environment
  `wait-on` command can wait for local files.

**Comment by poislagarde** [comment]
I understand, it could get a little messy. Thank you for the quick answer and help though, and `wait-on` works great in my case. Thanks again!

**Comment by robario** [comment]
@mysticatea 
I know how @poislagarde feel.

```
{
    "build": "webpack",
    "watch": "npm-run-all build -p watch:*",
    "watch:webpack": "webpack --watch",
    "watch:depends_on_webpack": "some_processing ./www/bundle.js",
}
```

In the case of above, webpack's first build runs twice. (And the first build is slower than the continued build.)
The idea of using `wait-on` sounds good.

```
    "watch:depends_on_webpack": "wait-on ./www/bundle.js && some_processing ./www/bundle.js",
```

However it is not waiting if `./www/bundle.js` already exists.
I want to wait for the completion of the process rather than the file creation.

Should I do like this?

```
    "watch:depends_on_webpack": "rimraf ./www/bundle.js && wait-on ./www/bundle.js && some_processing ./www/bundle.js",
```

Otherwise wait for the stdout as described in this issue?
However, I think it is difficult that implement to wait for stdout.

**Comment by poislagarde** [comment]
@robario if it helps, I ended up doing this:

```json
"scripts": {
    "prebuild": "rimraf _built",
    "build": "tsc",
    "watch": "npm-run-all prebuild -p watch:*",
    "watch:tsc": "tsc -w",
    "watch:nodemon": "wait-on _built/server.js && nodemon _built/server.js --watch _built"
}
```

`wait-on` works fine here because the `_built` directory is cleared (`rimraf _built`) before.

**Comment by robario** [comment]
@poislagarde
Thank you for telling me the actual situation.
I started using rimraf&wait-on, too.

**Comment by Download** [comment]
@robario Please do not use single-ampersand (`&`) operator as it fails on Windows (poor Windows dev here has to keep fixing NPM scripts that are failing on my machine :( )

**Comment by mysticatea** [comment]
Closing as I don't want to add this feature.
Thank you for making request.
