### ISSUE TITLE
The Single-Quoted task does not works.

### ISSUE THREAD

**Issue by robario** [mysticatea/npm-run-all#45]
```
{
  "scripts": {
    "woks": "run-s \"echo\"",
    "notworks": "run-s 'echo'",
    "echo": "echo"
  }
}
```

```
$ npm run notworks
> run-s 'echo'
ERROR: Task not found: "'echo'"
```

```
$ npm run works
> run-s "echo"
```

**Comment by robario** [comment]
Is it a restriction of `minimatch`?

**Comment by mysticatea** [comment]
On Windows, `'` is not an enclosing character. It's the specification of cmd.exe.
You need to use double quotes on Windows.

**Comment by mysticatea** [comment]
`run-s 'foo bar'` has 2 arguments (`'foo` and `bar'`) on Windows.

**Comment by robario** [comment]
Well..., is it a restriction of `npm`?
If so, I apologize it and please close this issue.

**Comment by mysticatea** [comment]
Yes. `npm run-script` is using `child_process.exec`, then `child_process.exec` of Node.js is using cmd.exe on Windows...
