### ISSUE TITLE
Plan to drop supports for Node 0.10 and 0.12

### ISSUE THREAD

**Issue by mysticatea** [mysticatea/npm-run-all#52]
https://github.com/nodejs/LTS#readme

I will drop supports for both 0.10 and 0.12 at the end of 2016.

**Comment by mysticatea** [comment]
I'm considering to change the path of `npm` that `npm-run-all` is using to run tasks.

Currently, `npm-run-all` is using the result of `which npm` command (via `cross-spawn` module).

The new behavior is that `npm-run-all` uses `npm` that `NPM_EXECPATH` environment variable specified. This environment variable is made by `npm` automatically in `npm run`. This implies that `npm-run-all` uses `npm` which runs itself. As a side-effect, if it run `npm-run-all` in `yarn run` command, `npm-run-all` run tasks with `yarn`.
If the `NPM_EXECPATH` environment variable did not find, `npm-run-all` keeps the current behavior.

One concern, someone has a local-installed `npm` then `npm-run-all` is using it to run tasks. In this case, probably this change effects negatively.

**Comment by ericanderson** [comment]
It would seem to be expected behavior, that if I installed a local npm, that said npm is what I would want to npm-run-all anyway.

**Comment by mysticatea** [comment]
I dropped supports for Node 0.x: https://github.com/mysticatea/npm-run-all/releases/tag/v4.0.0
