### ISSUE TITLE
Feature: default values for argument placeholders.

### ISSUE THREAD

**Issue by mysticatea** [mysticatea/npm-run-all#54]
run-s "run-server -- --port {0:=8080}"            # --> run-s "run-server -- --port 8080"
    run-s "run-server -- --port {0:=8080}" -- 3000    # --> run-s "run-server -- --port 3000"

If the default value of a placeholder is nothing and the argument for the placeholder is nothing, the placeholder will be removed.

    run-s "run-server -- --port {0}"            # --> run-s "run-server -- --port "
    run-s "run-server -- --port {0}" -- 3000    # --> run-s "run-server -- --port 3000"

**Comment by robario** [comment]
@mysticatea 

`:=` means use default value and assignment to the variable.
So `run-s "run-server -- --port {0:=8080} {0}"` should be `run-s "run-server -- --port 8080 8080"`

`:-` means just use default value.
So `run-s "run-server -- --port {0:-8080} {0}"` should be `run-s "run-server -- --port 8080"`

**Comment by robario** [comment]
You can choose from two way.

1. support `:-` only
2. support `:-` and `:=` then implement each as "use default value" and "use default value and assignment"
