### ISSUE TITLE
How can I define npm tasks watch patterns ?

### ISSUE THREAD

**Issue by mitermayer** [mysticatea/npm-run-all#56]
I was wondering how can we define watch patterns, and can a single watch dispatch to multiple scritps ?

An ideal world we could in a single folder watch dispatch different tasks depending on the file type change:

1. setup a folder to be watched
2. based on the files that have changed on that folder execute some npm run scripts in parallalel

example for a pacakge.json with `test`, `compile`:

* watch folder `src/`
* when *test.js changes, run tests
* when *.ts changes compile then run tests

**Comment by mysticatea** [comment]
Thank you for this issue.

Examples:

```json
{
    "scripts": {
        "watch": "run-p watch:*",
        "watch:mocha": "mocha \"src/**/*.text.js\" --watch",
        "watch:tsc": "tsc . --watch"
    }
}
```

```json
{
    "scripts": {
        "test": "mocha \"src/**/*.text.js\"",
        "build": "tsc .",
        "watch": "run-p watch:*",
        "watch:mocha": "npm run test -- --watch",
        "watch:tsc": "npm run build -- --watch",
    }
}
```

```json
{
    "scripts": {
        "test": "mocha \"src/**/*.text.js\"",
        "build": "tsc .",
        "watch": "run-p \"{build,test} -- --watch\""
    }
}
```

**Comment by mitermayer** [comment]
Thanks for the reply, I had previously thought that npm-run-all also had a helper for watching, but I understand now that it is responsibility of the npm run task itself to do it. I manage to find a workaround by using this plugin together with node-watch, and using npm-run-all api to call tasks based on specific changes.
