### ISSUE TITLE
Extract cross-platform spawn with `kill`

### ISSUE THREAD

**Issue by kentcdodds** [mysticatea/npm-run-all#59]
I'd really love to use this functionality in [`p-s`](http://npm.im/p-s). Any chance you'd be willing to open source that bit as a separate module (or would you be ok with me doing it)?

Also, I totally love this module. Like a ton. Thank you!

**Comment by kentcdodds** [comment]
To be clear, these are the files that'd need to be extracted and open sourced:

- [`src/lib/spawn.js`](https://github.com/mysticatea/npm-run-all/blob/master/src/lib/spawn.js)
- [`src/lib/spawn-win32.js`](https://github.com/mysticatea/npm-run-all/blob/master/src/lib/spawn-win32.js)
- [`src/lib/spawn-posix.js`](https://github.com/mysticatea/npm-run-all/blob/master/src/lib/spawn-posix.js)

**Comment by mysticatea** [comment]
Thank you for this issue.

Interesting.
I searched cross-platform `kill` package in npm, [kill-tree](https://www.npmjs.com/package/tree-kill) seems it.
If it add the method to the returned value (`ChildProcess` instance) of `spawn`, maybe we can offer it to `cross-spawn` package.... as `killTree()` or something like.

**Comment by kentcdodds** [comment]
I think we should do [this](https://github.com/IndigoUnited/node-cross-spawn/issues/40). Is that what you mean by:

> If the offer is rejected, I'm happy to make the package with you!

? :)

**Comment by mysticatea** [comment]
Yes, I agree, https://github.com/IndigoUnited/node-cross-spawn/issues/40 is best.

> If the offer is rejected, I'm happy to make the package with you!

I had misunderstood this English sentence ( (or would you be ok with me doing it) ).
Just I thought I might need 2nd plan to make a pakcage like `cross-spawn-with-kill`.

**Comment by kentcdodds** [comment]
Gotcha. We'll see what they say!

**Comment by kentcdodds** [comment]
Looks like the request was denied. `cross-spawn-with-kill` coming soon :)

I'll let you know when I start working on it. If you beat me to it then that's fine :)

**Comment by kentcdodds** [comment]
Alrighty, I'm going to try to knock this out!

**Comment by kentcdodds** [comment]
It's a thing now! Thanks a ton!

https://github.com/kentcdodds/cross-spawn-with-kill

**Comment by mysticatea** [comment]
Awesome!
