### ISSUE TITLE
If one task crashes, others keep running

### ISSUE THREAD

**Issue by BigstickCarpet** [mysticatea/npm-run-all#6]
When running multiple tasks simultaneously, if one task crashes, the others continue running, with no easy way to kill them.   For example:

```json
"scripts": {
    "runall": "npm-run-all --parallel watch webserver",
    "watch": "gulp watch",
    "webserver": "node server.js"
}
```

When I run `npm run runall`, it runs `watch` and `webserver` in parallel.  Let's say that `watch` crashes for some reason (exits with a non-zero exit code).  When this happens, `npm-run-all` also exits.  But `webserver` is still running.  If I re-run `npm run runall`, I now get an error because the `webserver` can't start because the already-running instance is blocking the port number.

It would be nice if when one of the tasks crashes, `npm-run-all` would kill the other tasks too.

**Comment by BigstickCarpet** [comment]
FYI - [concurrently](https://www.npmjs.com/package/concurrently) does this via a `--kill-others` argument

**Comment by mysticatea** [comment]
Thank you for the report.
I will check it this evening (JST).

**Comment by mysticatea** [comment]
I reproduced this issue. 
You are right, when one of tasks clashed, `npm-run-all --parallel` should kill all tasks.

But I wander, I thought child tasks are killed by OS when the parent task exited....

**Comment by BigstickCarpet** [comment]
Yeah, I'm confused by that as well.  I thought the child tasks would automatically get killed, but they don't.  

It might be worth looking at the source code for [concurrently](https://www.npmjs.com/package/concurrently), since I've noticed that when I force-quit concurrently (via Ctrl+C), it _does_ kill the child processes.  Maybe it has something to do with how the processes are launched?

**Comment by mysticatea** [comment]
I tried to send SIGTERM to remained tasks, but.... https://github.com/npm/npm/issues/4603 :(

**Comment by mysticatea** [comment]
Next, I will try to emulate `npm run` behavior without using npm tomorrow.

**Comment by BigstickCarpet** [comment]
It sucks that npm has that issue.  I wonder how soon they plan to fix it?

Thanks for looking into this.  I appreciate it!

**Comment by mysticatea** [comment]
I published `v1.2.6`.

On this version, when `npm-run-all` runs tasks in parallel, if one of tasks exited with an error, `npm-run-all` kills other tasks.
`npm` does not forward signals to child process, so `npm-run-all` tries to find child processes of `npm`, and send a `SIGTERM` signal to them.

Its test is here: https://github.com/mysticatea/npm-run-all/blob/v1.2.6/test/parallel.js#L36-58

Please try it!

**Comment by BigstickCarpet** [comment]
Awesome!  Testing it right now....

**Comment by BigstickCarpet** [comment]
Seems to work pretty well.  It's not 100% perfect, but that's to be expected, given the hoops you're having to jump through. 

Thanks!!!

**Comment by FDiskas** [comment]
got this issue again: If I hit CTRL + C it exits to fast - docker-compose does not stops containers but nextjs node server is stopped correctly
```json
    "dev": "npm-run-all -l --race clean --parallel dev:docker dev:next",
    "dev:docker": "docker-compose -f docker-compose-dev.yml up",
    "dev:next": "next",
    "clean": "rimraf .next",
```
```
"npm-run-all": "^4.1.5",
```
