### ISSUE TITLE
pass args

### ISSUE THREAD

**Issue by tomdavidson** [mysticatea/npm-run-all#62]
Awesome. Lovin npm-run-all and the consolidated efforts! 

I would like to pass in arguments such as:

```js
    "compile:ts:cjs": "tsc --p tsconfig.commonjs.json $*",
    "watch:compile:ts": "npm-run-all -p compile:ts:* -- -w",
    "watch:compile:ts:cjs": "npm run compile:ts:cjs -- -w"
```

`$ npm run compile:ts:cjs -- -w` works as expected and tsc invokes with the watch flag, as does `$ npm run watch:compile:ts:cjs`"

`$ npm run watch:comile:ts` does not work as desired, tsc does not watch. [npm-debug.log](https://gist.github.com/tomdavidson/2f749c5e1643d54cfa0df37fc23f837f)

Ultimately I want to be able to  `"watch": "npm-run-all -p watch:* "` and to snag several different watchers and not just `tsc -w`.

Is there an existing option of accomplishing the same or is this an enhancement?

**Comment by mysticatea** [comment]
Thank you for this issue!

`npm-run-all` has the capability of passing arguments. [More info...](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#run-with-arguments)
In short, you can enclose script name and arguments by double quotes.

`npm-run-all -p "compile:ts:* -- -w"` is meant `npm run compile:ts:* -- -w`-like.

**Comment by tomdavidson** [comment]
This is too cool. Sorry I over look the detail in the docs and thanks for the quick response. Works perfectly:

```js
    "compile:ts": "npm-run-all -p \"compile:ts:* -- {*}\" --",
    "compile:ts:cjs": "tsc --p tsconfig.commonjs.json $*",
    "watch": "npm-run-all -p \"compile:ts:* -- {*}\" -- -w",
```
