### ISSUE TITLE
npm-run-all doesn't work with pnpm

### ISSUE THREAD

**Issue by zkochan** [mysticatea/npm-run-all#67]
We started to use npm-run-all at [pnpm](https://github.com/rstacruz/pnpm) and we noticed that it doesn't work when installed with pnpm. The reason is that we create a proxy bin file (this is needed to allow running deps with the --preserve-symlinks option). As a result [this check](https://github.com/mysticatea/npm-run-all/blob/master/src/bin/common/bootstrap.js#L55) in npm-run-all fails. What is the reason for that check? Can it be removed?

I filed a defect on pnpm to fix this issue https://github.com/rstacruz/pnpm/issues/413. However, currently I don't know how this can be fixed on pnpm side. Could this be fixed on npm-run-all side?

**Comment by mysticatea** [comment]
Thank you for this issue.

The check is used for tests.
It's the official way to distinguish the entry file: https://nodejs.org/api/modules.html#modules_accessing_the_main_module

**Comment by mysticatea** [comment]
That check was needed in order to measure coverage.
I'm using `nyc` now, so I might be possible to remove the check.

**Comment by zkochan** [comment]
That would be awesome! Thank you!

**Comment by iamstarkov** [comment]
yay 🎉
