### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by odinho** [mysticatea/npm-run-all#68]
Hey, it's possible to `alias npm=yarn`, but it would be nice if it was at all possible to make it use choose yarn when it's available.

This issue is for tracking that.

**Comment by trevordmiller** [comment]
Looks like it may be in progress here: https://github.com/mysticatea/npm-run-all/pull/66

**Comment by odinho** [comment]
It's not really the same.  That is aliasing npm=yarn.  Whilst npm-r won't use yarn if itself was dispatched by yarn.

That was what I was thinking:

If running:

    yarn foo

Then `run-s` would use `yarn` for running it.  If the starting command was `npm run foo`, then `run-s` would use npm.

**Comment by mysticatea** [comment]
Thank you for this issue. And I'm sorry for late response.

`yarn` is fast and convenient, yes.
I'm hoping https://github.com/yarnpkg/yarn/issues/941 to be implemented.

I'm not sure that this feature is in the scope of `npm-run-all`.
But if I add it, it may be `--exe-path=yarn` to replace `npm` by the argument.

**Comment by arxpoetica** [comment]
I noticed https://www.npmjs.com/package/yarn-run-all is aliased to this repo—*super* confusing. Maybe document in the `README`?

**Comment by odinho** [comment]
The problem of it /not/ being in scope of `npm-run-all` is that `npm-run-all` as well as `run-s` are hard coded into the scripts.

In other words, if I want to run `yarn`, much of the dispatching will actually be running npm instead.  I appreciate that it's not really straight forward.  But it would be nice if `yarn myscript` would always run yarn and not weirdly decide to run `npm`.

Adding `--exec-path=yarn` won't really help at all here, since the feature would not be meant for the one writing `package.json` but running it. E.g. an env var could work.

Anyway, this issue is there for tracking it and having a place to keep the discussion.

**Comment by mysticatea** [comment]
@arxpoetica Oh, thank you for the report. Granted it's confusing, but I don't have the control of that package. I'm considering whether `npm-run-all`'s README should mention it or not.

@odinho Hmm, can I know what tool is executing `npm-run-all`? If yes, `npm-run-all` can use the tool which is executing itself to execute scripts.

**Comment by mysticatea** [comment]
I'm considering to use `NPM_EXECPATH` environment variable: https://github.com/mysticatea/npm-run-all/issues/52#issuecomment-264068108
`yarn` sets the path of `yarn` to the environment variable.

**Comment by mysticatea** [comment]
Now `npm-run-all` uses `NPM_EXECPATH`: https://github.com/mysticatea/npm-run-all/releases/tag/v4.0.0

**Comment by odinho** [comment]
Excellent, thank you :)

**Comment by jonataswalker** [comment]
Not sure If I understand how to use `npm-run-all` with `yarn`.

**Comment by arxpoetica** [comment]
@jonataswalker:

```bash
"script1": "...",
"script2": "...",
"examplescript": "NPM_EXECPATH=$npm_execpath npm-run-all script1 script2"
```

Etc.

**Comment by jonataswalker** [comment]
Thank you @arxpoetica but here (Arch) worked without any adding:

```json
"build": "run-p build:js build:css"
```
And then `yarn build`.

**Comment by arxpoetica** [comment]
Yes, but where did you set the correct path? Is it hardcoded in a bash or zsh file?

**Comment by jonataswalker** [comment]
I did nothing, at all. zsh here.

**Comment by arxpoetica** [comment]
I suspect it's still using NPM under the surface. Can you confirm? Screenshot? If it's actually using Yarn, you'll see something like the following:

![image](https://cloud.githubusercontent.com/assets/111424/23578984/26a1fbc4-00b1-11e7-8865-38ca9c4ba324.png)

Etc.

**Comment by jonataswalker** [comment]
There you are.

![selection_001](https://cloud.githubusercontent.com/assets/10571881/23579259/60a3e96a-00c8-11e7-967c-62dd693f45c7.png)

**Comment by mysticatea** [comment]
`NPM_EXECPATH=$npm_execpath` is unnecessary since v4.0.1 (#84).
