### ISSUE TITLE
How to pass custom command line options through?

### ISSUE THREAD

**Issue by mhulse** [mysticatea/npm-run-all#69]
**Using:** `npm-run-all@3.1.1`, `npm 3.10.8` and `node v7.0.0`.

In my `package.json` I have:

```json
"from-cover": "run-s cover archive --",
```

… which points to:

```json
"cover": "node . cover",
"archive": "node . archive",
```

When I run my scripts using:

```bash
$ npm run from-cover -- --skip
```

The `--skip` option does not get passed through.

Is this the expected behavior? Feature? Bug? Possible?

Thanks!

**Note:** If I leave off `--` from `run-s cover archive`, I get this output:

```bash
$ npm run from-cover -- --skip
ERROR: Invalid Option: --skip
```

**Comment by mysticatea** [comment]
Thank you for this issue.

It should be possible. You can use [argument placeholders](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md#argument-placeholders).
For example:

```json
{
  "scripts": {
    "from-cover": "run-s \"cover -- {@}\" \"archive -- {@}\" --",
    "cover": "node . cover",
    "archive": "node . archive"
  }
```

`run-s "cover -- {@}"` is evaluated to `npm run cover -- {@}`, then the `{@}` will be replaced by arguments preceded by `--`.

**Comment by mhulse** [comment]
> run-s "cover -- {@}" "archive -- {@}" is evaluated to npm run cover -- {@} and npm run archive -- {@}, then the {@} will be replaced by arguments preceded by --.

Ahhhhhh, I see! So I would have to do that for every command in the sequence. Interesting!

I will try that tonight and report my findings. Looks like it will work though.

I'm also curious to compare that to the raw npm version (e.g., `foo: "node . baz && node . bar && node . gloop` etc.).

Thanks for the help @mysticatea! I greatly appreciate it! :octocat:

**Comment by mhulse** [comment]
@mysticatea your suggestion worked perfectly. Thank you!

I spent a few minutes looking at how folks do the same thing using vanilla npm script running, and it looked much more syntactically messy. While the additional escaped quotes and curly braces etc. make the JSON a little less readable (which was the primary reason why I wanted to use npm-run-all) it reads much better than what I have seen when not using npm-run-all! 😆 

Anyway, many many thanks for the help and for the awesome code! :octocat:

**Comment by pedroabreu** [comment]
I'm not able to pass down specific options to my child task

In this scenario:

```
{
  "scripts": {
    "from-cover": "run-s \"cover -- {@}\" archive --",
    "cover": "node . cover",
    "archive": "node . archive"
}
```

if I try to execute `npm run from-cover --try=1,2,3` it will evaluate to `npm run cover -- "1,123"` instead of `npm run cover -- --try=1,2,3`

From the comments in this issue it seems ti should work like this 🤔

**Comment by pedroabreu** [comment]
Managed to make it work. Was missing `--` in my script call 🙄 

For reference this is the correct script call:

`npm run from-cover -- --try=1,2,3`

**Comment by matthias-ccri** [comment]
Not working for me...

Scripts:
```
    "lint": "run-p 'lint:* {@}'",
    "lint:src": "eslint 'src/app/**/*.ts' --format codeframe",
```


```
$ yarn lint --fix
yarn run v1.22.5
$ run-p 'lint:*' --fix
ERROR: Invalid Option: --fix
error Command failed with exit code 1.
```

Update:
```
# doesn't work:
$ yarn lint -- --fix
# works:
$ yarn lint -- -- --fix
```
I guess npm-run-all is expecting yarn run to pass a `--` but yarn strips it?
