### ISSUE TITLE
No coloring in shell

### ISSUE THREAD

**Issue by halt-hammerzeit** [mysticatea/npm-run-all#7]
When I do `npm test` it outputs colored log.
When I do it with your tool there's no color.

**Comment by mysticatea** [comment]
Probably the test tool stops coloring in some uses.
If you use mocha, please try the `--colors` option, likely [this](https://github.com/mysticatea/npm-run-all/blob/master/package.json#L19).

**Comment by halt-hammerzeit** [comment]
@mysticatea  Wow, really, that helped mocha, and webpack too.

**Comment by jedmao** [comment]
Doesn't fix non-mocha commands though. For example, I'm running `istanbul check-coverage` and the colors are lost.
