### ISSUE TITLE
Run task after parallel tasks completed

### ISSUE THREAD

**Issue by garygreen** [mysticatea/npm-run-all#72]
It's not clear whether this is currently possible. 

For instance

A, B should run in parallel
Once A + B are both run / completed, run C.

How would one achieve this?

**Comment by mysticatea** [comment]
Thank you for this issue.

Maybe:

    $ npm-run-all -p A B -s C

Or:

    $ run-p A B && npm run C

**Comment by junejie** [comment]
Hi,

I tried it but it dint work.
Notes: A and B is a service (like mockserver and express )

The issue is it didn't execute the C.

**Comment by mysticatea** [comment]
@junejie Yes. Above examples run C *after* both A and B are finished. Services don't finish.

I guess you can use [wait-on](https://www.npmjs.com/package/wait-on) CLI command.

```json
{
    "scripts": {
        "test":        "run-p test:*",
        "test:server": "node lib/server.js",
        "test:mocha":  "wait-on http://localhost:3000/ && mocha \"test/*.js\""
    },
    "devDependencies": {
        "mocha":       "^3.2.0",
        "npm-run-all": "^4.0.0",
        "wait-on":     "^2.0.1"
    }
}
```

The `wait-on` command waits `http://localhost/` to be prepared, then it finishes.

**Comment by junejie** [comment]
I solved it. I created a http checker for it.
and `wait-on` do a greate job. I dont event know `wait-on` exist.

**Comment by tobiastom** [comment]
@junejie How did you solve the issue that `node lib/server.js` would never be stopped?

**Comment by junejie** [comment]
@tobiastom  i just send it in background `npm run test:server &`

**Comment by fatso83** [comment]
Shouldn't issues like this be closed? This is not a problem of this project.

**Comment by mysticatea** [comment]
Yes, thank you.
