### ISSUE TITLE
Can't run npm link

### ISSUE THREAD

**Issue by JuanCaicedo** [mysticatea/npm-run-all#78]
I get the following error if I run `npm link`. This is using node v4.4.5

```
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/JuanCaicedo/.nvm/versions/node/v4.4.5/bin/node" "/Users/JuanCaicedo/.nvm/versions/node/v4.4.5/bin/npm" "link"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /Users/JuanCaicedo/.nvm/versions/node/v4.4.5/lib/node_modules/npm-run-all/bin/run-p/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/JuanCaicedo/.nvm/versions/node/v4.4.5/lib/node_modules/npm-run-all/bin/run-p/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JuanCaicedo/code/personal/npm-run-all/npm-debug.log
```

**Comment by JuanCaicedo** [comment]
I found that this works if you run `npm run build`. Maybe there's away to run a pre-link script?

**Comment by mysticatea** [comment]
Yes, this repository does not include the build result. If you want to use it without `npm install npm-run-all`, you need to run `npm run build`.
I'm closing this issue since I intent that this module is used via `npm install npm-run-all`.

**Comment by JuanCaicedo** [comment]
SGTM! I was trying to link it for development, maybe it would be good to have a development doc. If so, let me know and I can write down some notes as I'm getting started
