### ISSUE TITLE
Swallowing Colors

### ISSUE THREAD

**Issue by TheAlphaNerd** [mysticatea/npm-run-all#8]
It would appear that I am losing all the pretty colors from various CLI's that I run with this tool.

Will try digging in to see if there is a sane way to keep to colors.

**Comment by mysticatea** [comment]
Thank you for the report!

Please see also #7.

**Comment by mysticatea** [comment]
I guess choke is detecting whether or not stdout is cli, and stdout is piped this tool...

**Comment by TheAlphaNerd** [comment]
repo in question

--> https://github.com/TheAlphaNerd/engine-seed/tree/update-bin

**Comment by mysticatea** [comment]
Could you try `eslint --color` and `jscs --colors` options?

**Comment by TheAlphaNerd** [comment]
jscs has no --color or --colors options

it only has an option to turn colors off ```-n```

**Comment by mysticatea** [comment]
Oh...

**Comment by jedmao** [comment]
Same problem here >_<

**Comment by mysticatea** [comment]
I will try to fix this.
Please give me time to investigate.

**Comment by jedmao** [comment]
@mysticatea passing `{ stdio: 'inherit' }` to the spawn command options gives you colors.

**Comment by mysticatea** [comment]
I apologize for my late response.

I released `v1.2.8`, using `inherit` option: https://github.com/mysticatea/npm-run-all/commit/736dee0023630f8b9ce7b72e6ec79af49b35821d
Thanks @jedmao!
