### ISSUE TITLE
combine -s, -p -r

### ISSUE THREAD

**Issue by serapath** [mysticatea/npm-run-all#88]
i tried to specify a task like this: `npm-run-all --serial a --parallel --race b c d`

my intention is to first let a setup task called `a` run and then run three processes that do not end.
* `b` is starting a server
* `c` is starting a watcher
* `d` is testing some stuff

one `d` finishes, i'd like `c` and `b` to end which i think the `--race` flag is used for, but it seems to not work when a `--serial` flag is present.

I was wondering if maybe a new version can be released that adds support for https://www.npmjs.com/package/subarg which might make it easier to group stuff.

**Comment by mysticatea** [comment]
Thank you for this report.

It's a bug, I will fix it.

> I was wondering if maybe a new version can be released that adds support for https://www.npmjs.com/package/subarg which might make it easier to group stuff.

Personally, I'm unfamiliar with the brackets in CLI parameters. I prefer below or something like for now.

    $ run-s a b && run-p --race c d
